# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eab7abe81f799817d6430514d20e8ccf1f013209567a7a923a826f663daf0b4e694974e1662c3d2936c93a35746d709667f4422c6b65da054c3643387fe240f

test:
  secret_key_base: a9b031c59cd6e41be7a9361645c3e0004b9ff9f57b554ab066b95d33fe6bc87a5dee1dd8b1b4b2d28d844818d77c5bd79c0d93fefee749e9e364425a64305b0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
